# h2 database config
spring:
  datasource:
    url: jdbc:h2:~/testgit s
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
